name: Yggdrasil

on:
  push:
  pull_request:
  release:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  build-linux:
    name: Build & Test (Linux, Go ${{ matrix.goversion }})
    needs: [lint]
  
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.16", "1.17", "1.18"]
        
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goversion }}

    - name: Build Yggdrasil
      run: go build -v ./...

    - name: Unit tests
      run: go test -v ./...

  build-windows:
    name: Build & Test (Windows, Go {{ matrix.goversion }})
    needs: [lint]
    
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.16", "1.17", "1.18"]
        
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goversion }}

    - name: Build Yggdrasil
      run: go build -v ./...

    - name: Unit tests
      run: go test -v ./...
      
  build-macos:
    name: Build & Test (macOS, Go {{ matrix.goversion }})
    needs: [lint]
    
    strategy:
      fail-fast: false
      matrix:
        goversion: ["1.16", "1.17", "1.18"]
        
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goversion }}

    - name: Build Yggdrasil
      run: go build -v ./...

    - name: Unit tests
      run: go test -v ./...
